[build]
  command = "npm install && npm run build"
  publish = "dist"

# PROXY: send all /api/* from Netlify → Vercel API
[[redirects]]
  from = "/api/*"
  to   = "https://docvai-dashboard-git-main-tubaycom-gmailcoms-projects.vercel.app/api/:splat"
  status = 200
  force  = true

# SPA fallback so /overview etc. work
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
